### ISSUE TITLE
Issues with the plugin

### ISSUE THREAD

**Issue by XhmikosR** [jekyll/jekyll-seo-tag#64] opened 2016-03-01 17:24 UTC
So, I'm trying to get the plugin in Bootstrap v4-dev branch and I notice the following (sorry for not splitting them)

1. `<meta name="twitter:description" content="" />` while `<meta name="description" content="Bootstrap, a sleek, intuitive, and powerful mobile first front-end framework for faster and easier web development.">`. The description is set in _config.yml
2. The title is wrong if I set `title=false`. `<meta property="og:title" content="Introduction" />` and `"headline": "Introduction",` vs `<title>Introduction &middot; Bootstrap</title>`. 

The branch for testing is here: https://github.com/twbs/bootstrap/compare/v4-dev...v4-dev-xmr-jekyll-social-tag

**Comment by pathawks** [comment] 2016-03-01 17:39
> The title is wrong if I set title=false. <meta property="og:title" content="Introduction" /> and "headline": "Introduction", vs <title>Introduction &middot; Bootstrap</title>.

But the title of the page _is_ “Introduction”

**Comment by XhmikosR** [comment] 2016-03-01 17:48
The title is `Introduction &middot; Bootstrap`, not only `Introduction`.

**Comment by pathawks** [comment] 2016-03-01 19:34
Yes, I understand that that is what is contained in the `<title>` tag, but that isn’t _really_ the title of the page. If you were to list all of the pages in a table of contents, they wouldn’t all have “Bootstrap” tacked onto the end.

Twitter limits this field to 70 characters, so it is important to avoid cluttering this with anything extra.

**Comment by XhmikosR** [comment] 2016-03-01 19:49
I see. Then that makes sense.

The first issue is valid though.

**Comment by XhmikosR** [comment] 2016-03-01 19:54
Although, I do have a case where I see both types.

```html
<title>Downloads &middot; MPC-HC</title>
<meta name="description" content="Download our binaries, source code, etc.">

        <!-- Begin Jekyll SEO tag v1.3.1 -->
<meta property="og:title" content="Downloads" />
<meta name="description" content="Download our binaries, source code, etc." />
<meta property='og:description' content="Download our binaries, source code, etc." />
<link rel="canonical" href="https://mpc-hc.org/downloads/" />
<meta property='og:url' content='https://mpc-hc.org/downloads/' />
<meta property="og:site_name" content="MPC-HC" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@mpc_hc" />
<meta name="twitter:title" content="Downloads - MPC-HC" />
<meta name="twitter:description" content="Download our binaries, source code, etc." />
<meta property="fb:app_id" content="1552669435051497" />
<script type="application/ld+json">
  {
    "@context" : "http://schema.org",
    "@type" : "WebPage",
    "headline": "Downloads",
    "description": "Download our binaries, source code, etc.",
    "logo": "https://mpc-hc.org/assets/img/logo-256x256.png",
    "url" : "https://mpc-hc.org/downloads/"
  }
</script>
<!-- End Jekyll SEO tag -->
```

`twitter:title` isn't the same as `headline` and includes the `MPC-HC` part with a random separator also (not `&middot;`).

**Comment by pathawks** [comment] 2016-03-01 20:09
Looking at the code, I'm not sure how this is possible. Can you maybe submit a failing test?

**Comment by XhmikosR** [comment] 2016-03-01 20:10
No idea how to do that, sorry.

Probably it's an edge case due to `title=false`.

**Comment by pathawks** [comment] 2016-03-02 05:01
As far as your first point, the code outputs the same thing for `description` and `twitter:description`. I have no idea how one but not the other could be blank.

```html
  <meta name="description" content="{{ seo_description }}" />
  <meta name="twitter:description" content="{{ seo_description }}" />
```

To your second point, it [looks like `twitter:title` is using `seo_title` instead of `seo_page_title`](https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/template.html#L129). This feels like a bug to me.

**Comment by XhmikosR** [comment] 2016-03-02 09:27
About the first problem, it's because the code checks for `page.description` and not `site.description`. Which is right technically, since it's bad to use the same page description.

**Comment by XhmikosR** [comment] 2016-03-02 09:29
Also, to correct my initial statement, in Bootstrap, meta description is set in _header.html and not in _config.yml.

**Comment by XhmikosR** [comment] 2016-03-02 20:05
Another thing I was wondering, should the `sameAs` show in all pages or only in homepage?

**Comment by pathawks** [comment] 2016-03-02 20:16
`sameAs` is page specific. It will be included for any page that has the property set, _and_ include site wide links on home and about pages.

**Comment by pathawks** [comment] 2016-03-03 00:55
With the recent changes, the output is now:

```html
<!-- Begin Jekyll SEO tag v1.3.2 -->
<meta property="og:title" content="Introduction" />
<link rel="canonical" href="http://getbootstrap.com/getting-started/introduction/" />
<meta property="og:url" content="http://getbootstrap.com/getting-started/introduction/" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@getbootstrap" />
<script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "WebPage",
    "headline": "Introduction",
    "url": "http://getbootstrap.com/getting-started/introduction/"
  }
</script>
<!-- End Jekyll SEO tag -->
```

This seems to be working as intended, so I am closing this issue. If you run into any more problems, please do open an issue for each one :+1:

**Closed by pathawks** 2016-03-03 00:55 UTC
