### ISSUE TITLE
The property logo is not recognized by Google for an object of type WebSite

### ISSUE THREAD

**Issue by XhmikosR** [jekyll/jekyll-seo-tag#91] opened 2016-05-20 14:13 UTC
https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fjekyllrb.com%2F

```
https://jekyllrb.comimg/logo-2x.png (The property logo is not recognized by Google for an object of type WebSite.)
```

**Comment by nzcage** [comment] 2016-05-23 09:53
If it's about AMP, AMP has it's on value in google structure data tool. Otherwise, this might  help you:
https://productforums.google.com/forum/#!topic/webmasters/zBUGR_AuJKY

**Comment by XhmikosR** [comment] 2016-05-23 11:52
@nzcage: this isn't AMP. It's Jekyll's own website.

The problem arises with the default type which is Website, which doesn't support the logo property.

So, maybe it would be better to not output logo here.

**Comment by pathawks** [comment] 2016-07-08 18:40
Duplicate of #89

**Closed by pathawks** 2016-07-08 18:40 UTC
