### ISSUE TITLE
Fix `og:image` to fall back to the site image if one exists

### ISSUE THREAD

**Issue by aarongustafson** [jekyll/jekyll-seo-tag#168] opened 2017-03-31 18:57 UTC
The `meta` element doesn’t show up at all if `page.image` doesn’t exist.

**Comment by pathawks** [comment] 2017-04-01 05:19
Duplicate of #97 #95

**Closed by pathawks** 2017-04-01 05:19 UTC

**Comment by pathawks** [comment] 2017-04-01 05:22
The reason we want the user to explicitly define an image instead of just falling back to the logo or something is because there may be instances where a user would rather include no image than include the logo. If this is not the case, the user can easily specify a site-wide default image to use.

**Comment by benbalter** [comment] 2017-04-03 13:58
See https://github.com/jekyll/jekyll-seo-tag#setting-a-default-image

**Comment by mrcoles** [comment] 2018-12-23 02:55
@benbalter the link has changed, it is now: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#setting-a-default-image
