### ISSUE TITLE
broken author meta tag

### ISSUE THREAD

**Issue by gschueler** [jekyll/jekyll-seo-tag#186] opened 2017-04-11 19:12 UTC
using github pages, previously this worked in our _config.yml

~~~{.yaml}
author:
  twitter: username
~~~

I think github pages upgraded to jekyll-seo-tag 2.2.0, and now that breaks the HTML page, by generating:

~~~{.html}
<meta name="author" content="{"twitter"=>"username"}" />
~~~

The readme specifies this as a valid config: https://github.com/jekyll/jekyll-seo-tag#author-information

changing the to `author: name` fixes the HTML issue

**Comment by pkra** [comment] 2017-04-12 09:26
We encountered the same problem (though with `first_name` and `last_name` instead of the OP's `twitter`); also on github pages (but I can reproduce the issue locally as well). 

This results in artifacts in the compiled HTML (for lots of old content).

Might be due to https://github.com/jekyll/jekyll-seo-tag/pull/103.

**Comment by benbalter** [comment] 2017-04-12 14:48
I *think* this should be fixed on `master` after https://github.com/jekyll/jekyll-seo-tag/pull/184.

**Comment by smashism** [comment] 2017-04-28 14:38
Unfortunately I'm experiencing this issue on my site as well. This does not appear to be fixed.

**Comment by DirtyF** [comment] 2017-04-28 15:28
@smashism with latest gem 2.2.1? Can you provide a link to a repository?

**Comment by mehmandarov** [comment] 2017-05-19 13:20
Similar issue: https://github.com/jekyll/jekyll-seo-tag/issues/210

**Comment by benbalter** [comment] 2017-05-22 14:51
#210 is a distinct issue. I'm going to call this closed on the latest version.

**Closed by benbalter** 2017-05-22 14:51 UTC
